### ISSUE TITLE
Not able to connect to the http server in the final step

### ISSUE THREAD

**Issue by code4fish** [omarabid59/cloud_ml_webrtc#1]
After following each step, during the final step in order to launch the website, I'm not able to connect. It just says connection refused.

![image](https://user-images.githubusercontent.com/5293227/54330368-5cd06500-4650-11e9-8209-df0e309ad7e2.png)

What is causing this and what can be done to solve it? Is there something that need to be changed in the Google Cloud platform?

Thanks

**Comment by code4fish** [comment]
Update:
So I was finally able to connect. The issue was related to firewall settings in the Google Cloud platform which I fixed by applying two new rules:

![image](https://user-images.githubusercontent.com/5293227/54350899-40045380-4689-11e9-8c9c-5180c9a25498.png)

After I got in, I had to approve camera access and was shown this page:

![image](https://user-images.githubusercontent.com/5293227/54350729-e734bb00-4688-11e9-920a-d98c37e4e220.png)

But the canvas in which the video should be shown is not visible. I've tried multiple browsers and devices, but cannot get the video feed.

What can be done to get the video showing?

**Comment by omarabid59** [comment]
hey, sorry about the late reply. the first thing I would do is check the Web Browser Console, it's located under Developer Tools for Google Chrome and Web Console under Firefox. Are you getting some error?

**Comment by zobrathemanish** [comment]
Yes, in firefox it is saying Cross-Origin Blocked.

**Comment by amylyt000** [comment]
Yeah, it has an error in init_screen.js saying wcSendVideoCanvas is not definded. How to solve it?
<img width="517" alt="Screen Shot 2019-05-29 at 4 04 40 PM" src="https://user-images.githubusercontent.com/33010886/58597201-c01f6b80-822b-11e9-9ac2-b4a05d823dd8.png">

**Comment by code4fish** [comment]
@amylyt000 were you able to find a way around it?

**Comment by amylyt000** [comment]
Yes, I added `var wcVideoCanvas = document.createElement('canvas'),
    ctxWcVideo = wcVideoCanvas.getContext('2d');`
in webserver/public/static/scripts/constants.js to get the problem solved.

**Comment by ocervell** [comment]
This is still an issue, and the fix by @amylyt000 works

**Comment by dimitri320** [comment]
This was already in the repo, but I also needed to add this to make it work:

`wcSendVideoCanvas = document.createElement('canvas')`
